### PR TITLE
vagrant: added centos8 support

### LINKED ISSUE #71: Unable to install docker-ce on Centos 8 box image.
**Bug Report**
As Red Hat explicitly excluded Docker CE on CentOS 8 in favor of Podman, docker-ce doesn't get installed while using ``BOX_IMAGE="centos/8"``

**Expected behavior:**
Docker gets installed successfully.

**Deviation from expected behavior:**
``` Docker CE Stable - x86_64                        67 kB/s | 3.5 kB     00:00    
    master: Error: 
    master:  Problem: package docker-ce-3:19.03.11-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed
    master:   - cannot install the best candidate for the job
    master:   - package containerd.io-1.2.10-3.2.el7.x86_64 is excluded
    master:   - package containerd.io-1.2.13-3.1.el7.x86_64 is excluded
    master:   - package containerd.io-1.2.13-3.2.el7.x86_64 is excluded ```

logs: https://hastebin.com/elocuceyeq

**How to reproduce it (minimal and precise):**
<!-- Please let us know any circumstances for reproduction of your bug. -->
```make up BOX_OS=centos VAGRANT_DEFAULT_PROVIDER=libvirt KUBERNETES_VERSION="v1.17.5" MASTER_CPUS=2 NODE_CPUS=2 MASTER_MEMORY_SIZE_GB=4 NODE_COUNT=1 NODE_MEMORY_SIZE_GB=4 DISK_COUNT=2 DISK_SIZE_GB=25 POD_NW_CIDR=192.168.123.0/24 KUBE_NETWORK="calico" BOX_IMAGE="centos/8"
```

**Environment**:
* OS of the machine (e.g. from `/etc/os-release`): Centos 8
* Kernel of the machine (e.g. `uname -a`): ```Linux n59.gusty.ci.centos.org 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
* `make versions` output: 

```
=== BEGIN Version Info ===
Repo state: 8ed4982bd0e596ea1331a6f95304ea1130185015 (dirty? NO)
make: /usr/bin/make
kubectl: /usr/bin/kubectl
grep: /usr/bin/grep
cut: /usr/bin/cut
rsync: /usr/bin/rsync
openssl: /usr/bin/openssl
/dev/urandom: OK
Vagrant version:
Vagrant 2.2.7
=== END Version Info ===
```

### PR DESCRIPTION
**Pull request by galexrt**
This PR adds support for centos8 and splits up `centos` to `centos7` and
`centos` "target" OSes to allow both OS versions to be used if needed.
Force calico as canal seems to be broken under CentOS 8.

Resolves #71

Signed-off-by: Alexander Trost <galexrt@googlemail.com>

### CODE REVIEW

**Comment by Yuggupta27** [comment]
Hi @galexrt , will only mentioning ```BOX_OS=centos8``` be sufficient to launch vagrant boxes in centos8 OS?
Just using the BOX_OS parameter lands me with Centos7 nodes.
```master: ++ uname -a
    master: Linux master 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux ```
See: Line 6381 https://hastebin.com/ijoforanum

**Comment by galexrt** [comment]
@Yuggupta27 Yes, that is sufficient. But you need to use the latest commit (a new release tag will be added after my bags testing has been merged), you are on 5e5a... which is a few commits behind master.

**Comment by Yuggupta27** [comment]
@galexrt I used the master branch but due to some reason still, Centos 7 boxes are created :(

**Comment by galexrt** [comment]
@Yuggupta27 Post the `make versions` output of your repo.

**Comment by Yuggupta27** [comment]
Here 
```
=== BEGIN Version Info ===
Repo state: 5e5a7959bb2ef482540da6257292b552caf0552f (dirty? NO)
make: /usr/bin/make
kubectl: /usr/bin/kubectl
grep: /usr/bin/grep
cut: /usr/bin/cut
rsync: /usr/bin/rsync
openssl: /usr/bin/openssl
/dev/urandom: OK
Vagrant version:
Vagrant 2.2.7
=== END Version Info ===
```

**Comment by Yuggupta27** [comment]
I just used my fork to print the kernel version, I didn't make any other changes.

**Comment by galexrt** [comment]
@Yuggupta27 Well that is the reason why the commit isn't the same as current "actual" `master` branch.

The reason why CentOS 7 is still used is because of this line https://github.com/galexrt/k8s-vagrant-multi-node/blob/master/vagrantfiles/centos8/common#L1, I forgot to change it to `centos/8`.

Testing CentOS 8 locally again now, confirms that it is not working (CNI is broken) and I'll play around with it a bit more to see if I'm able to workaround the CNI being broken.

**Pull request merged**
